version: '3.9'

services:
  frontend:
    image: ${REGISTRY}/essg-frontend:${TAG:-latest}
    container_name: frontend-essg-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${PROD_API_URL}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  back-office:
    image: ${REGISTRY}/essg-back-office:${TAG:-latest}
    container_name: back-office-prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${PROD_API_URL}
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001', (r) => {if (r.statusCode !== 200) throw new Error(r.statusCode)})"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  app-network:
    driver: bridge
