export const endpoints = {
  formations: '/formations',
  formationById: (id: number) => `/formations/${id}`,
  formationBySlug: (slug: string) => `/formations/slug/${slug}`,
  formationSearch: '/formations/search',
  news: '/news',
  newsById: (id: number) => `/news/${id}`,
  newsBySlug: (slug: string) => `/news/slug/${slug}`,
  newsSearch: '/news/search',
  projects: '/projects',
  projectById: (id: number) => `/projects/${id}`,
  projectBySlug: (slug: string) => `/projects/slug/${slug}`,
  projectSearch: '/projects/search',
  partners: '/partners',
  partnerById: (id: number) => `/partners/${id}`,
  partnerBySlug: (slug: string) => `/partners/slug/${encodeURIComponent(slug)}`,
  partnerSearch: '/partners/search',
  staff: '/ressources-humaines',
  staffById: (id: number) => `/ressources-humaines/${id}`,
  staffBySlug: (slug: string) => `/ressources-humaines/slug/${slug}`,
  staffSearch: '/ressources-humaines/search',
  messages: '/messages',
  verifyEmail: '/messages/verify-email',
  admissions: '/admissions',
  admissionsCheckDuplicate: '/admissions/check-duplicate',
  settingsPublic: '/settings/public',
  health: '/health',
} as const;
