export { default as actualiteService } from './actualite.service';
export { default as admissionService } from './admission.service';
export { createContactMessage } from './contact.service';
export { default as formationService } from './formation.service';
export { default as partenaireService } from './partenaire.service';
export { default as projetService } from './projet.service';
export { default as ressourceHumaineService } from './ressource-humaine.service';
export { default as settingsService } from './settings.service';
export * from './admission.service';
export * from './contact.service';
export * from './settings.service';
